### ISSUE TITLE
Pin unread manga to the top of library

### ISSUE THREAD

**Issue by bdashore3** [Aidoku/Aidoku#15]
Add an option to place unread mangas on the top of the library. This requires a rewrite on how the badge code works to avoid any race conditions.

**Comment by Spjoti** [comment]
A small thing that I think could go well with this is when you refresh, have a number at the top of how many unread chapters you have left like:

“9 Unread Chapters”
“3 New Updates”
“All caught up :)”

I don’t know what would count as new versus just unread but as it is right now it would be nice to get feedback if there are no new updates.

**Comment by Skittyblock** [comment]
@Spjoti do you mean like a counter separate from the unread badges in the manga? I think it might be good to have some sort of indicator for new chapter updates, but that's not on my priority list at the moment.

I think that's better for a separate enhancement issue though, since this is just for pinning manga.
