### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [Aidoku/Aidoku#203]
Given https://github.com/Aidoku/Aidoku/blob/main/LICENSE covers
the translations in https://github.com/Aidoku/Aidoku/tree/main/Shared/Localization
they can't be made https://hosted.weblate.org/projects/aidoku/strings/#information Apache 2.0
without all the translators agreeing to do so first.

Can be fixed by selecting "GPL version 3 or later" in 
https://hosted.weblate.org/settings/aidoku/strings/
and
https://hosted.weblate.org/glossary/aidoku/strings/

**Comment by Skittyblock** [comment]
I'm a little confused. I don't mind making the localizations GPLv3, but they're all crowdsourced and all the contributors agree to the Apache 2.0 license by contributing any translations. Aidoku, under GPLv3, then freely uses the localizations that are under Apache 2.0, while Aidoku remains under GPLv3 (since the licenses are compatible).

What does the Quran app have to do with Aidoku? Are there duplicate translation strings? Isn't that just coincidental, since each localization has to be contributed to Aidoku separately and anyone who does agrees to the Apache 2.0 license?

**Comment by comradekingu** [comment]
(I was looking at more recent Hosted Weblate projects and reused one of the tabs to get the URL without checking first.)

Anything contributed henceforth on Hosted Weblate will be Apache 2.0,
whereas the stuff that was already imported is and remains GPLv3. (Or maybe those strings were contributed on different terms somehow.)
Importing any Apache 2.0 string into the project also makes them GPLv3 here,
so I don't understand the appeal of Apache 2.0.
I think that is how it works when contributing to an already started translation too,
as it contributes to a "work" in the copyright sense.

**Comment by Skittyblock** [comment]
Weblate has been used pretty much from the beginning, and was put in place as soon as I added localization support. The localizations that were imported (English) were entirely from me, so there isn't an issue relicensing them as Apache 2.0.

The appeal of Apache 2.0 is simply so that other projects can reuse the localizations without having to really worry about the stricter licensing terms of GPLv3 (not that many would really care to reuse them, it just seems better to use a more permissible license for non-code).
