### ISSUE TITLE
Big loading "stutter" when using pillar box together with crop border.

### ISSUE THREAD

**Issue by Jamerrone** [Aidoku/Aidoku#340]
Not sure if this is related to my other issue (broken pillar box). This was not an issue on v0.6.5 build 1 but it is in build 2.

https://github.com/Aidoku/Aidoku/assets/16142485/4b392c8e-20e9-46c3-becc-6f12c2b53762

**Comment by Skittyblock** [comment]
After double checking this I think, firstly, this doesn't have anything to do with pillarboxing (it happens regardless of whether it's on or off), and secondly, is unavoidable since crop borders takes processing time. The resolution to this would be with webtoon reader preloading, which I'll hopefully implement soon.

**Comment by Jamerrone** [comment]
What about doing it on download? I know that this won't apply to everyone, but if the cropping happens beforehand it will make things a lot smoother, right?

**Comment by Skittyblock** [comment]
wdym on download? like when downloading a chapter to read offline? that doesn't really make sense since the option is togglable so we need to account for people turning the setting on or off
