### ISSUE TITLE
Feature request: Custom AltStore repository

### ISSUE THREAD

**Issue by bazzadazza72** [Aidoku/Aidoku#484]
I would like to make a contribution in the form of a custom AltStore repository to make sideloading Aidoku easier, now that AltStore supports user-defined repositories without being a Patreon member. 

This is essentially a bump to #102, however, I believe custom repositories were locked unless you were a patron when that issue was opened.

Let me know your thoughts, and if this is something that should happen, I'd be happy to get started.

**Comment by Skittyblock** [comment]
this is obviously a duplicate since you mentioned it... you could just comment on that one

but as for having an altstore repo, we wouldn't endorse a non-official one, but the only way we would have an official one is if we were to auto-generate it with github workflows or something, but i haven't really looked into the feasibility of that. if you want to discuss it's best to use the #app-dev channel on discord
