### ISSUE TITLE
Not loading all manga chapters

### ISSUE THREAD

**Issue by portbusy** [Aidoku/Aidoku#74]
I wanted to start a 350+ chapter manga but only the last 20 results are loaded from the application. I went to check the source link (MangaDex) and noticed that only the last page containing the last chapters were being loaded and that to access the other chapters it was necessary to change the index used for pagination. 
![IMG_8354](https://user-images.githubusercontent.com/50581327/175053887-1b7cd593-77ee-46b1-b9e3-ce2fb36e132b.PNG)
![IMG_8355](https://user-images.githubusercontent.com/50581327/175053903-eacbd9a3-28d6-4835-96cb-3a24fc802869.PNG)

**Comment by Skittyblock** [comment]
Pulling to refresh will fix this. The reason this happens is because when a title is added to your library, all the chapters are cached in the background. If you add a title to your library and then immediately go to your library to open it, it will only show the chapters that have been cached so far.

I'll leave this open since I should probably come up with a way to make it display chapters from the source if it hasn't finished caching them all yet.

**Comment by Skittyblock** [comment]
I think the source is only displaying chapters for language you have selected. This isn't an Aidoku issue, but just how that specific source operates.
