### ISSUE TITLE
Double page odd numbering

### ISSUE THREAD

**Issue by phiefferj24** [Aidoku/Aidoku#95]
double page but the first page is automatically wide. See cubari

**Comment by Skittyblock** [comment]
I think this is unnecessary with #96 and #445

**Comment by dyphire** [comment]
This is actually different from #96 and #445. In Japanese comics, the first page is often the cover, which will lead to incorrect double-page splicing under the double-page layout. The solution is to add the first page as a cover separately and stitch it with a blank page.

This is a screenshot of the function options in suwatte:
![IMG_5136](https://github.com/user-attachments/assets/2e76d1a2-cf7e-47f9-bcb3-2022515838e6)

**Comment by Skittyblock** [comment]
nah, this is the same as #96. that's just additionally saying there should be a toggle for it (and corresponding keybind).

**Comment by dyphire** [comment]
> nah, this is the same as #96. that's just additionally saying there should be a toggle for it (and corresponding keybind).

Incorrect. The feature request in #96 it makes is that when one page is a wide image in double page mode the wide image should be displayed separately to avoid incorrect splicing. Whereas this feature request means that when the first page is a cover (not a wide image) it will lead to incorrect splicing of the rest of the pages in double page mode, it should be provided with the ability to display the first page separately in order to splice correctly.

The purpose of both is to fix the wrong splicing in double page mode, but they are not the same kind of feature request, one is to auto-detect the wide image and the other is to display the first page separately.

**Comment by Skittyblock** [comment]
i meant #445, i commented the wrong one. feel free to go to mangadex and press the o key to see
